[package]
name = "concrete_nn_architectures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = "0.1.11"
itertools = "0.10.1"
anyhow = "1.0.8"
csv = "1.1"
tch = "0.6.1"
